server.port: 8084

spring:
  application.name: blablatest
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
      fail-on-unwrapped-type-identifiers: false
    deserialization.fail-on-unknown-properties: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    joda-date-time-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

  flyway:
    table: schema_version
